// <auto-generated />
namespace TP4.EF.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Products : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Products));
        
        string IMigrationMetadata.Id
        {
            get { return "202109192321518_Products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
